### ISSUE TITLE
::v-deep selector syntax highlighting support

### ISSUE THREAD

**Issue by hyvyys** [vuejs/vetur#1419]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.22.2
- VS Code version: 1.38.0

## Problem

I believe the ::v-deep selector is not supported by the syntax highlighter in Vetur.

![image](https://user-images.githubusercontent.com/20814638/64431807-6eed0680-d0bb-11e9-91ac-5853a8d0a4cf.png)
![image](https://user-images.githubusercontent.com/20814638/64431831-7b715f00-d0bb-11e9-9e51-9779f13772c3.png)

## Reproducible Case

```scss
.checkbox-small.ui-checkbox {
  margin: 0;
  font-size: 1em;
  align-self: center;

  ::v-deep .ui-checkbox__checkmark {
    height: 1rem;
    width: 1rem;
    margin-top: 0.2rem;
  }
  ::v-deep .ui-checkbox__label-text {
    font-size: 1em;
    margin-left: 0.15em;
  }
}

.nav-wrapper {
  width: 0;

  ::v-deep .positioned {
    background: $light;
    right: $vuebar-width;
    width: 175px;
    @include pseudo;
    &::after {
      left: 100%;
      background: $light;
      width: $vuebar-width;
    }
  }
}
```

**Comment by andrew-boyd** [comment]
Our team is also experiencing this issue.

**Comment by octref** [comment]
Upstream issue: https://github.com/atom/language-sass/issues/254

**Comment by Herbata-Sys** [comment]
Issue still occurs

**Comment by wowissu** [comment]
```scss
$vdeep: "::v-deep"

#{$vdeep} .subclass {
// ... 
}
```
