### ISSUE TITLE
Formatting maybe change upper case letter to lower case letter

### ISSUE THREAD

**Issue by zbjumper** [vuejs/vetur#719]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: v0.11.7
- VS Code version: 1.21.0

## Problem

When I format Code with shortcut option + shift + F, some upper case letter in base64 encode image was change to lower case letter .

The origin css is：
```css
.avatar-image {
  width: 100%;
  height: 100%;
  border-radius: 50%;
  background-size: 100% 100%;
  background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAKAAAACgCAMAAAC8EZcfAAABR1BMVEUAAADf3+fh4erf3+jk5Ozj4+r29/3n6O/q6vHp6vL9///////m5u7n5+7j4+v4+Pjl5e3m5+7q6vHr7fL09Pv9/f/h4enl5e329/3z8/n////j5Ovh4ej29/3k5Ozl5ez29/zp6fD29/339/309Prx8fTz8/n6+vr09Pz////j4+r19v3o6O/k5O3n6O/29/3o6O/29/3p6fH4+P/19//s7PXx8/r3+f7h4en19v3i4urq6/H19/3z8/rp6fDp6fL////k5Oz29/z29/zp6vH2+P319fr4+P/w8PP29/329/329/319v3p6vD19/z19/z2+P32+P31+P31+P/h4er19v3c3OT19vze3ubz9Pnu7vTl5ezq6/Lz9Pvi4unm5+7j4+vw8ffh4urg4Ojf3+bu7/bp6fDo6O/r7PPp6vHs7fTx8vjr6/N+3B3zAAAAVnRSTlMA/vH82uv5m0doGQW6tuQSycF6NSYK/cWrJAf49/bhzcWCgXdaMSsWDQLt697TqJ+Ih31FPTw4HfPp6KiakXBjA9zBvq+JY0ki9N7d0c26t3FwZ07y7ChWXlEAAAZhSURBVHjazdtnVxQxFAbgO7MFloWlCFJsCAh2VBDsvff63sw22tL9/58FUSNnHbhJJsM+P2BPTnJLMslSEvoLbT3ZUi48mckAmczJMFfK9rQV+unoTfV1ZcMAMYIw29XXTUfl/IPeEAJh74PzlLr2zosKYirX2U4penX1FoyFV19RKgaulWCpdG2AfJvsCeAg6Jkkn+auwJW6cox8ac8iEVk/CdN+Gok5nfwQuweRqN6E6/fZDBKWOUvJuXkHHty5Sckodip4obqKlIBzIby5eI6c3cjAo0yf6/IOwrNBp2U+FsK70KGzFBRSoB5aFz+FVKgbZKUNqWkjC12w0AiCBix0kakLZ2BEVarlbf5tu1ytKBg5Yzq+LAzUNyNuEm3WYSBLRkzmb2GbY2wvQO6Mp/hbr/EBausQ6/KRv5WIDxFVINUmrn+Q2mKBLQWhswn3j5WIRSJptqiCqP8GkFmssVBtUTpCQV8eCaXhxwakgRiO0GF6pPPH7GOEg3SIG5Cp19jMMmT6DglABREVsaFI+svnEgnAMhsrQyYsUrxOcYJYkPa9Top1E0J6gT0sMm5SnBxk1thKFTJ3KMY1yKga22m4tbzuDGTW2dImZDLd9D+DniJQq8GlXLfDpof46Sdop2anIbTB1soQOu0wgaixPdhP4WMILbOA8xpnrWs01tlBFVJztN8VSJXZwRKkrtA+5+A1BDWInbM8Byt2sgKpHiLtfACpOjtZhFRw3qQLaxV2sgCxa6Tdge8k1u1YrER/9UNujZ1UITdMf1yFXJWdbEDuKv1xC0hrgGXI3dJt2MBGegNEe9NRyf8MbkETH58uYlfrJQlyv6s0fmm5MrNjr1Y/gIkFdrIOEw9oVy/2tFon2dFLu0LsabFevCukHVMww04UjEzpD25iETuowUzf/irYSjtqfTXxGGaq/luxltWNWKySThLrLIEhxQ4CmAmIJmFqia1FMNVPBYi5B+EPmCo03cu1xsejv9qoB8ZqbEvBVA9lYWyDLZVhLEslGFtmS4swVqIczEW+c1jLUQgx96/85kI6CXMBW1mBuZOUgYWy5xTRMhTAQp0t1GEhQ5Bxn8JVWCHIuFeaZdhQlIGV1ZQmMGM7wBXPKawHeBJ2qn5roC4zISxFHpuIFgpbnfuzFEs5KsFW2V+N1kqC7Zb7y49IwVaWBmFt2VsJ1HoFW37nXc0a7LXRQwg4heEWHDykV3Cx6qeFaPNEARyobT7EtoKDgIi+wUXgY5OlhUTyOmP1naEGJ1n94tfWpocSrT0jogKcLPKBFuCkQEQDDbioC47C1hoD+h7HVuCrieibnE64WPGyT9V3Yc5BWPG5xA9p14CCgy2PSaJG9LtGW4o9lpkc7bkLe2Vmf0F41ehVj+XRaQn2JmmHS6FplCUHYgVLOcf/fy1vsEhtwzKV2+iPDgVTan2b5aKqRSg2pkxfX2qLZTa1tN6AmdOk3YCJhSW2slWHiT7SischpdYitrZUgdjxos3fwIJqjZ1Eawoyz+hfHaIpbFTZXW1TNMSgg/bpFSyuHl4KQ+yl/foPzbG1Gmveh9gYJrNXtpWIExUt4EBnzP4stLLKiVuqI17jGDV5j1ib7MWGQpz31GwyiOu5EXtSq8TVwElqErstXOOkyP/3eZf+Z+AEmqlV9ipaRrMTI/RfBb/JK38P94JiXBY8FrQnfuzzmOL0H0/g7t/5Fi/op1j3RQcizyO8T/EuXBadeL2O8PIFOkCHzuQqp2hLZ3AHHWhC6beq6dE3AWqCDvFMfxNKVV2X6IM9uqy/7KZpaS8AH5F2UBhWOHULOgAPMXtcT2CKtoHjsyQyEdT5CCyvTJBQ3w8+Aj/6SOwTH4HPZOA5p+46GbnHKbtHO1p4Dv/OX4vG4WeyMJHnlOQnyMrL15yK1zNkae42p+D2HFnreMLePe0gB4/G2LOxR+Rmxusy354hZx1PmbVWWt4/LoyfYi9OjV+gZMwPsQdD85Scl285YW9fUqJGxvKcoPzYCCWtP8F1nh4mH4bv5ROZvXvD5Mv8/VPOqXt/nnyaen6JHVy6PkW+Fb8O5S3XduhrkVLR/WWUjY1+6aYUDY9/OGUQeB/Ghyl1xdmxJ3nBwj4Zmy3SURmYGZ8e/R6bEqPT4zMDdPS6Z19cnx76OPruzaV8/tKbd6Mfh6avv5hLJOZ+AkhxbdinmDhqAAAAAElFTkSuQmCC);
}
```

and it change to：

```css
.avatar-image {
  width: 100%;
  height: 100%;
  border-radius: 50%;
  background-size: 100% 100%;
  background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAKAAAACgCAMAAAC8EZcfAAABR1BMVEUAAADf3+fh4erf3+jk5Ozj4+r29/3n6O/q6vHp6vL9///////m5u7n5+7j4+v4+Pjl5e3m5+7q6vhr7fl09pv9/f/h4enl5e329/3z8/n////j5Ovh4ej29/3k5Ozl5ez29/zp6fD29/339/309Prx8fTz8/n6+vr09Pz////j4+r19v3o6O/k5O3n6O/29/3o6O/29/3p6fH4+P/19//s7PXx8/r3+f7h4en19v3i4urq6/H19/3z8/rp6fDp6fL////k5Oz29/z29/zp6vH2+P319fr4+P/w8PP29/329/329/319v3p6vD19/z19/z2+P32+P31+P31+P/h4er19v3c3OT19vze3ubz9Pnu7vTl5ezq6/Lz9Pvi4unm5+7j4+vw8ffh4urg4Ojf3+bu7/bp6fDo6O/r7PPp6vHs7fTx8vjr6/N+3b3zaaaavnrstlma/vH82uv5m0doGQW6tuQSycF6NSYK/cWrJAf49/bhzcWCgXdaMSsWDQLt697TqJ+Ih31FPTw4HfPp6KiakXBjA9zBvq+JY0ki9N7d0c26t3FwZ07y7ChWXlEAAAZhSURBVHjazdtnVxQxFAbgO7MFloWlCFJsCAh2VBDsvff63sw22tL9/58FUSNnHbhJJsM+P2BPTnJLMslSEvoLbT3ZUi48mckAmczJMFfK9rQV+unoTfV1ZcMAMYIw29XXTUfl/IPeEAJh74PzlLr2zosKYirX2U4penX1FoyFV19RKgaulWCpdG2AfJvsCeAg6Jkkn+auwJW6cox8ac8iEVk/CdN+Gok5nfwQuweRqN6E6/fZDBKWOUvJuXkHHty5Sckodip4obqKlIBzIby5eI6c3cjAo0yf6/IOwrNBp2U+FsK70KGzFBRSoB5aFz+FVKgbZKUNqWkjC12w0AiCBix0kakLZ2BEVarlbf5tu1ytKBg5Yzq+LAzUNyNuEm3WYSBLRkzmb2GbY2wvQO6Mp/hbr/EBausQ6/KRv5WIDxFVINUmrn+Q2mKBLQWhswn3j5WIRSJptqiCqP8GkFmssVBtUTpCQV8eCaXhxwakgRiO0GF6pPPH7GOEg3SIG5Cp19jMMmT6DglABREVsaFI+svnEgnAMhsrQyYsUrxOcYJYkPa9Top1E0J6gT0sMm5SnBxk1thKFTJ3KMY1yKga22m4tbzuDGTW2dImZDLd9D+DniJQq8GlXLfDpof46Sdop2anIbTB1soQOu0wgaixPdhP4WMILbOA8xpnrWs01tlBFVJztN8VSJXZwRKkrtA+5+A1BDWInbM8Byt2sgKpHiLtfACpOjtZhFRw3qQLaxV2sgCxa6Tdge8k1u1YrER/9UNujZ1UITdMf1yFXJWdbEDuKv1xC0hrgGXI3dJt2MBGegNEe9NRyf8MbkETH58uYlfrJQlyv6s0fmm5MrNjr1Y/gIkFdrIOEw9oVy/2tFon2dFLu0LsabFevCukHVMww04UjEzpD25iETuowUzf/irYSjtqfTXxGGaq/luxltWNWKySThLrLIEhxQ4CmAmIJmFqia1FMNVPBYi5B+EPmCo03cu1xsejv9qoB8ZqbEvBVA9lYWyDLZVhLEslGFtmS4swVqIczEW+c1jLUQgx96/85kI6CXMBW1mBuZOUgYWy5xTRMhTAQp0t1GEhQ5Bxn8JVWCHIuFeaZdhQlIGV1ZQmMGM7wBXPKawHeBJ2qn5roC4zISxFHpuIFgpbnfuzFEs5KsFW2V+N1kqC7Zb7y49IwVaWBmFt2VsJ1HoFW37nXc0a7LXRQwg4heEWHDykV3Cx6qeFaPNEARyobT7EtoKDgIi+wUXgY5OlhUTyOmP1naEGJ1n94tfWpocSrT0jogKcLPKBFuCkQEQDDbioC47C1hoD+h7HVuCrieibnE64WPGyT9V3Yc5BWPG5xA9p14CCgy2PSaJG9LtGW4o9lpkc7bkLe2Vmf0F41ehVj+XRaQn2JmmHS6FplCUHYgVLOcf/fy1vsEhtwzKV2+iPDgVTan2b5aKqRSg2pkxfX2qLZTa1tN6AmdOk3YCJhSW2slWHiT7SischpdYitrZUgdjxos3fwIJqjZ1Eawoyz+hfHaIpbFTZXW1TNMSgg/bpFSyuHl4KQ+yl/foPzbG1Gmveh9gYJrNXtpWIExUt4EBnzP4stLLKiVuqI17jGDV5j1ib7MWGQpz31GwyiOu5EXtSq8TVwElqErstXOOkyP/3eZf+Z+AEmqlV9ipaRrMTI/RfBb/JK38P94JiXBY8FrQnfuzzmOL0H0/g7t/5Fi/op1j3RQcizyO8T/EuXBadeL2O8PIFOkCHzuQqp2hLZ3AHHWhC6beq6dE3AWqCDvFMfxNKVV2X6IM9uqy/7KZpaS8AH5F2UBhWOHULOgAPMXtcT2CKtoHjsyQyEdT5CCyvTJBQ3w8+Aj/6SOwTH4HPZOA5p+46gbnhkbtho1p4dv/OX4vG4WeyMJHnlOQnyMrL15yK1zNkae42p+D2HFnreMLePe0gB4/G2LOxR+Rmxusy354hZx1PmbVWWt4/LoyfYi9OjV+gZMwPsQdD85Scl285YW9fUqJGxvKcoPzYCCWtP8F1nh4mH4bv5ROZvXvD5Mv8/VPOqXt/nnyaen6JHVy6PkW+Fb8O5S3XduhrkVLR/WWUjY1+6ayudy9/OGUQeB/Ghyl1xdmxJ3nBwj4Zmy3SURmYGZ8e/R6bEqPT4zMDdPS6Z19cnx76OPruzaV8/tKbd6Mfh6avv5hLJOZ+AkhxbdinmDhqAAAAAElFTkSuQmCC);
}
```

`Chinese is my mother language. My Engish is very poor.`
