### ISSUE TITLE
Request textDocument/formatting failed. Code: -32603 

### ISSUE THREAD

**Issue by pkjy** [vuejs/vetur#918]
- [X ] I have searched through existing issues
- [X ] I have read through [docs](https://vuejs.github.io/vetur)
- [X ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: 
- Vetur version: 0.12.7
- VS Code version: 1.27.2

## Problem

[Error - 10:32:50 AM] Request textDocument/formatting failed.
Message: Request textDocument/formatting failed with message: Cannot read property 'commentsOnTop' of undefined
  Code: -32603 

## Reproducible Case

1. Ctrl+Shift+P
2. Format Document
3. format didn't work and report error just like above.

**Comment by pkjy** [comment]
Already found the reason, post a issue for recording.
this bug happens when i use stylus and use comments in a wrong way. 
eg:
``` css
<style lang="stylus">
.login {
  width: 80%;
  /* position: absolute; */
  /* background: url("/static/login.png") no-repeat; */
}
</style>
```
these comments crash vetur. 
And stylus supports three kinds of comments: single-line, and multi-line comments, and multi-line buffered comments. [link](http://stylus-lang.com/docs/comments.html)
